import React from "react";
import {
  StandardContainer,
  TextContainerInner,
} from "../../containers/container";
import { CenteredHeading, BoldText } from "../../text/text";
import {
  SectionHeading,
  TermsPrivacyTitle,
  TermsPrivacyDate,
  TermsPrivacyLink,
} from "./terms_privacy_styles";
import { Center } from "../../alignment/Center";

const PrivacyPolicy = () => (
  <StandardContainer text>
    <TextContainerInner>
      <CenteredHeading> Privacy Policy</CenteredHeading>

      <TermsPrivacyDate>Last updated: February 10, 2020</TermsPrivacyDate>

      <p>
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>

      <br />

      <p>
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy.
      </p>
      <br />
      <br />
      <br />

      <Center>
        <TermsPrivacyTitle>Interpretation and Definitions</TermsPrivacyTitle>
      </Center>
      <br />

      <SectionHeading>Interpretation</SectionHeading>
      <p>
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <br />
      <br />

      <SectionHeading>Definitions</SectionHeading>
      <p>For the purposes of this Privacy Policy:</p>

      <br />
      <ul>
        <li>
          <BoldText>You</BoldText> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
        <br />
        <li>
          <BoldText>Company</BoldText> (referred to as either "the Company",
          "We", "Us" or "Our" in this Agreement) refers to Spekkly, LLC, 1234
          Mariposa Street, San Francisco, CA 94107.
        </li>
        <br />
        <li>
          <BoldText>Affiliate</BoldText> means an entity that controls, is
          controlled by or is under common control with a party, where "control"
          means ownership of 50% or more of the shares, equity interest or other
          securities entitled to vote for election of directors or other
          managing authority.
        </li>
        <br />
        <li>
          <BoldText>Account</BoldText> means a unique account created for You to
          access our Service or parts of our Service.
        </li>

        <br />
        <li>
          <BoldText>Website</BoldText> refers to Spekkly, accessible from
          spekkly.com
        </li>

        <br />
        <li>
          <BoldText>Service</BoldText> refers to the Website.
        </li>

        <br />
        <li>
          <BoldText>Country</BoldText> refers to: California, United States
        </li>

        <br />
        <li>
          <BoldText>Service Provider</BoldText> means any natural or legal
          person who processes the data on behalf of the Company. It refers to
          third- party companies or individuals employed by the Company to
          facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service or to assist the
          Company in analyzing how the Service is used.
        </li>

        <br />
        <li>
          <BoldText>Third-party Social Media Service</BoldText> refers to any
          website or any social network website through which a User can log in
          or create an account to use the Service.
        </li>

        <br />
        <li>
          <BoldText>Personal Data</BoldText> is any information that relates to
          an identified or identifiable individual.
        </li>

        <br />
        <li>
          <BoldText>Cookies</BoldText> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>

        <br />
        <li>
          <BoldText>Usage Data</BoldText> refers to data collected
          automatically, either generated by the use of the Service or from the
          Service infrastructure itself (for example, the duration of a page
          visit).
        </li>
      </ul>
      <br />
      <br />
      <br />

      <Center>
        <TermsPrivacyTitle>
          Collecting and Using Your Personal Data
        </TermsPrivacyTitle>
      </Center>
      <br />
      <br />

      <SectionHeading larger>Types of Data Collected</SectionHeading>
      <SectionHeading>Personal Data</SectionHeading>
      <p>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <br />

      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>

      <br />
      <br />

      <SectionHeading>Usage Data</SectionHeading>
      <p>Usage Data is collected automatically when using the Service.</p>
      <br />
      <p>
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <br />

      <p>
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </p>

      <br />

      <p>
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </p>
      <br />
      <br />

      <SectionHeading>Tracking Technologies and Cookies</SectionHeading>

      <p>
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service.
      </p>

      <br />
      <p>
        You can instruct Your browser to refuse all Cookies or to indicate when
        a Cookie is being sent. However, if You do not accept Cookies, You may
        not be able to use some parts of our Service.
      </p>

      <br />
      <p>
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
        remain on your personal computer or mobile device when You go offline,
        while Session Cookies are deleted as soon as You close your web browser.
      </p>

      <br />
      <p>
        We use both session and persistent Cookies for the purposes set out
        below:
      </p>
      <br />
      <br />

      <ul>
        <li>
          <BoldText> Necessary / Essential Cookies</BoldText>
          <br />
          <br />
          <p>Type: Session Cookies</p>

          <br />
          <p>Administered by: Us</p>
          <br />
          <p>
            Purpose: These Cookies are essential to provide You with services
            available through the Website and to enable You to use some of its
            features. They help to authenticate users and prevent fraudulent use
            of user accounts. Without these Cookies, the services that You have
            asked for cannot be provided, and We only use these Cookies to
            provide You with those services.
          </p>
        </li>
        <br />
        <br />

        <li>
          <BoldText> Cookies Policy / Notice Acceptance Cookies</BoldText>
          <br />
          <br />
          <p>Type: Persistent Cookies</p>

          <br />
          <p>Administered by: Us</p>
          <br />
          <p>
            Purpose: These Cookies identify if users have accepted the use of
            cookies on the Website.
          </p>
        </li>
        <br />
        <br />

        <li>
          <BoldText> Functionality Cookies</BoldText>
          <br />
          <br />
          <p>Type: Persistent Cookies</p>

          <br />
          <p>Administered by: Us</p>
          <br />
          <p>
            Purpose: These Cookies allow us to remember choices You make when
            You use the Website, such as remembering your login details or
            language preference. The purpose of these Cookies is to provide You
            with a more personal experience and to avoid You having to re-enter
            your preferences every time You use the Website.
          </p>
        </li>

        <br />
        <br />

        <li>
          <BoldText> Tracking and Performance Cookies</BoldText>
          <br />
          <br />
          <p>Type: Persistent Cookies</p>

          <br />
          <p>Administered by: Third-Parties</p>
          <br />
          <p>
            Purpose: These Cookies are used to track information about traffic
            to the Website and how users use the Website. The information
            gathered via these Cookies may directly or indirectly identify you
            as an individual visitor. This is because the information collected
            is typically linked to a pseudonymous identifier associated with the
            device you use to access the Website. We may also use these Cookies
            to test new advertisements, pages, features or new functionality of
            the Website to see how our users react to them.
          </p>
        </li>
      </ul>

      <br />
      <br />

      <SectionHeading larger>Use of Your Personal Data</SectionHeading>
      <p>The Company may use Personal Data for the following purposes:</p>
      <br />
      <ul>
        <li>
          <BoldText>To provide and maintain our Service</BoldText>, including to
          monitor the usage of our Service.
        </li>

        <br />
        <li>
          <BoldText>To manage Your Account:</BoldText> to manage Your
          registration as a user of the Service. The Personal Data You provide
          can give You access to different functionalities of the Service that
          are available to You as a registered user.
        </li>

        <br />
        <li>
          <BoldText>For the performance of a contract:</BoldText> the
          development, compliance and undertaking of the purchase contract for
          the products, items or services You have purchased or of any other
          contract with Us through the Service.
        </li>

        <br />
        <li>
          <BoldText>To contact You:</BoldText> To contact You by email,
          telephone calls, SMS, or other equivalent forms of electronic
          communication, such as a mobile application's push notifications
          regarding updates or informative communications related to the
          functionalities, products or contracted services, including the
          security updates, when necessary or reasonable for their
          implementation.
        </li>

        <br />
        <li>
          <BoldText>To provide You</BoldText> with news, special offers and
          general information about other goods, services and events which we
          offer that are similar to those that you have already purchased or
          enquired about unless You have opted not to receive such information.
        </li>

        <br />
        <li>
          <BoldText>To manage Your requests:</BoldText> To attend and manage
          Your requests to Us.
        </li>
      </ul>
      <br />
      <br />

      <p>We may share your personal information in the following situations:</p>
      <br />

      <ul>
        <li>
          <BoldText>With Service Providers:</BoldText> We may share Your
          personal information with Service Providers to monitor and analyze the
          use of our Service, to show advertisements to You to help support and
          maintain Our Service, to contact You, to advertise on third party
          websites to You after You visited our Service or for payment
          processing.
        </li>

        <br />
        <li>
          <BoldText>For Business transfers:</BoldText> We may share or transfer
          Your personal information in connection with, or during negotiations
          of, any merger, sale of Company assets, financing, or acquisition of
          all or a portion of our business to another company.
        </li>

        <br />
        <li>
          <BoldText>With Affiliates:</BoldText> We may share Your information
          with Our affiliates, in which case we will require those affiliates to
          honor this Privacy Policy. Affiliates include Our parent company and
          any other subsidiaries, joint venture partners or other companies that
          We control or that are under common control with Us.
        </li>

        <br />
        <li>
          <BoldText>With Business partners:</BoldText> We may share Your
          information with Our business partners to offer You certain products,
          services or promotions.
        </li>

        <br />
        <li>
          <BoldText>With other users:</BoldText> when You share personal
          information or otherwise interact in the public areas with other
          users, such information may be viewed by all users and may be publicly
          distributed outside. If You interact with other users or register
          through a Third-Party Social Media Service, Your contacts on the
          Third-Party Social Media Service may see Your name, profile, pictures
          and description of Your activity. Similarly, other users will be able
          to view descriptions of Your activity, communicate with You and view
          Your profile.
        </li>
      </ul>
      <br />
      <br />

      <SectionHeading larger>Transfer of Your Personal Data</SectionHeading>
      <p>
        Your information, including Personal Data, is processed at the Company's
        operating offices and in any other places where the parties involved in
        the processing are located. It means that this information may be
        transferred to — and maintained on — computers located outside of Your
        state, province, country or other governmental jurisdiction where the
        data protection laws may differ than those from Your jurisdiction.
      </p>

      <br />
      <p>
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
      </p>

      <br />
      <p>
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy and
        no transfer of Your Personal Data will take place to an organization or
        a country unless there are adequate controls in place including the
        security of Your data and other personal information.
      </p>
      <br />
      <br />

      <SectionHeading larger>Transfer of Your Personal Data</SectionHeading>
      <SectionHeading>Business Transactions</SectionHeading>

      <p>
        If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your
        Personal Data is transferred and becomes subject to a different Privacy
        Policy.
      </p>
      <br />

      <SectionHeading>Law enforcement</SectionHeading>
      <p>
        If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your
        Personal Data is transferred and becomes subject to a different Privacy
        Policy.
      </p>
      <br />

      <SectionHeading>Other legal requirements</SectionHeading>
      <p>
        The Company may disclose Your Personal Data in the good faith belief
        that such action is necessary to:
      </p>

      <br />
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>
          Prevent or investigate possible wrongdoing in connection with the
          Service
        </li>
        <li>
          Protect the personal safety of Users of the Service or the public
        </li>
        <li>Protect against legal liability</li>
      </ul>

      <br />
      <br />
      <SectionHeading>Security of Your Personal Data</SectionHeading>
      <p>
        The security of Your Personal Data is important to Us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially acceptable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security.
      </p>

      <br />
      <br />

      <Center>
        <TermsPrivacyTitle>
          Detailed Information on the Processing of Your Personal Data
        </TermsPrivacyTitle>
      </Center>

      <br />

      <p>
        Service Providers have access to Your Personal Data only to perform
        their tasks on Our behalf and are obligated not to disclose or use it
        for any other purpose.
      </p>
      <br />

      <SectionHeading>Analytics</SectionHeading>

      <p>
        We may use third-party Service providers to monitor and analyze the use
        of our Service.
      </p>

      <br />
      <ul>
        <li>
          <div>
            <BoldText>Google Analytics:</BoldText> Google Analytics is a web
            analytics service offered by Google that tracks and reports website
            traffic. Google uses the data collected to track and monitor the use
            of our Service. This data is shared with other Google services.
            Google may use the collected data to contextualise and personalise
            the ads of its own advertising network.
          </div>
          <br />

          <p>
            You can opt-out of having made your activity on the Service
            available to Google Analytics by installing the Google Analytics
            opt-out browser add-on. The add- on prevents the Google Analytics
            JavaScript (ga.js, analytics.js and dc.js) from sharing information
            with Google Analytics about visits activity.
          </p>

          <br />
          <p>
            {" "}
            For more information on the privacy practices of Google, please
            visit the Google Privacy & Terms web page:{" "}
            <TermsPrivacyLink
              target="_blank"
              href="https://policies.google.com/privacy?hl=en-US"
            >
              {" "}
              Google Analytics Privacy Policy{" "}
            </TermsPrivacyLink>
          </p>
        </li>
      </ul>
      <br />
      <br />

      <SectionHeading>Children's Privacy</SectionHeading>
      <p>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us. If We
        become aware that We have collected Personal Data from anyone under the
        age of 13 without verification of parental consent, We take steps to
        remove that information from Our servers.
      </p>

      <br />
      <p>
        We also may limit how We collect, use, and store some of the information
        of Users between 13 and 18 years old. In some cases, this means We will
        be unable to provide certain functionality of the Service to these
        users.
      </p>

      <br />
      <p>
        If We need to rely on consent as a legal basis for processing Your
        information and Your country requires consent from a parent, We may
        require Your parent's consent before We collect and use that
        information.
      </p>

      <br />
      <br />
      <SectionHeading>Links to Other Websites</SectionHeading>
      <p>
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party's site. We strongly advise You to review the Privacy Policy
        of every site You visit.
      </p>
      <br />

      <p>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>

      <br />
      <br />
      <SectionHeading>Changes to this Privacy Policy</SectionHeading>
      <p>
        We may update our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p>

      <br />
      <p>
        We will let You know via email and/or a prominent notice on Our Service,
        prior to the change becoming effective and update the "Last updated"
        date at the top of this Privacy Policy.
      </p>

      <br />
      <p>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>

      <SectionHeading>Contact</SectionHeading>
      <br />
      <p>
        If you have any questions about this Privacy Policy, You can contact us:
      </p>

      <ul>
        <li>
          By email:{" "}
          <TermsPrivacyLink target="_blank" href="mailto:support@spekkly.com">
            support@spekkly.com
          </TermsPrivacyLink>
        </li>
      </ul>
    </TextContainerInner>
  </StandardContainer>
);

export default PrivacyPolicy;
