export const CREATE_POST_ACTIVE_NAV = "CREATE_POST_ACTIVE_NAV";
export const CURRENT_PAGE_IS_VALID = "CURRENT_PAGE_IS_VALID";
export const LOADING = "LOADING";
export const FORM_TYPE = "FORM_TYPE";
export const EDIT_POST_ID = "EDIT_POST_ID";
