export const IS_SIGN_UP_OPEN = "IS_SIGN_UP_OPEN";
export const IS_LOGIN_OPEN = "IS_LOGIN_OPEN";
export const IS_EMAIL_LOGIN_OPEN = "IS_EMAIL_LOGIN_OPEN";
export const IS_EMAIL_SIGN_UP_OPEN = "IS_EMAIL_SIGN_UP_OPEN";
export const IS_FORGOT_PASSWORD_OPEN = "IS_FORGOT_PASSWORD_OPEN";
export const IS_RESET_PASSWORD_OPEN = "IS_RESET_PASSWORD_OPEN";
