export const CURRENT_CONVERSATION = "CURRENT_CONVERSATION";
export const NEW_MESSAGES = "NEW_MESSAGES";
export const NEW_CURRENT_CONVERSATION_MESSAGES =
  "NEW_CURRENT_CONVERSATION_MESSAGES";
export const LAST_MESSAGE_STATUS = "LAST_MESSAGE_STATUS";
export const MESSAGE_IMAGES_LOADED = "MESSAGE_IMAGES_LOADED";
export const DELETE_MESSAGES = "DELETE_MESSAGES";
export const UPDATE_CONVERSATION_ON_MESSAGE_DELETE =
  "UPDATE_CONVERSATION_ON_MESSAGE_DELETE";
export const RECIPIENT_ONLINE_CHANGE = "RECIPIENT_ONLINE_CHANGE";
export const MOBILE_ACTIVE_CONVERSATION = "MOBILE_ACTIVE_CONVERSATION";
