export const ACTIVE_NAV_INDEX = "ACTIVE_NAV_INDEX";
export const SETTINGS_EDIT_ACTIVE = "SETTINGS_EDIT_ACTIVE";
export const SETTINGS_EDIT_COMPLETE = "SETTINGS_EDIT_COMPLETE";
export const SETTINGS_LOADING = "SETTINGS_LOADING";
export const BLOCKED_USERS_ERROR = "BLOCKED_USERS_ERROR";
